# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
                ('create_time', models.DateField(auto_now=True)),
                ('modify_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.UserGroup'),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
    ]
